---
- name: Install nginx web server
  yum: name=nginx state=present update_cache=true
  become: true

- name: Enable nginx
  service: name=nginx enabled=yes
  become: true

- name: Start nginx
  service: name=nginx state=started
  become: true
